big_site/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.sitemaps.views import sitemap
from django.conf import settings
from django.conf.urls.static import static
from blog.sitemaps import PostSitemap

sitemaps = {'posts': PostSitemap}

urlpatterns = [
    path('blog/', include('blog.urls', namespace='blog')),
    path('admin/', admin.site.urls),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
    path('account/', include('account.urls', namespace='account')),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/urls.py
from django.urls import path
from . import views
from .feeds import LatestPostsFeed

app_name = 'blog'

urlpatterns = [
    path('', views.post_list, name='post_list'),
    path('tag/<slug:tag_slug>/', views.post_list, name='post_list_by_tag'),
    # path('', views.PostListView.as_view(), name='post_list'),
    path('<int:post_id>/share/', views.post_share, name='post_share'),
    path('<int:year>/<int:month>/<int:day>/<slug:post>/', views.post_detail, name='post_detail'),
    path('feed/', LatestPostsFeed(), name='post_feed'),
    path('search/', views.post_search, name='post_search')

]

blog/models.py
from django.contrib.auth.models import User
from django.db import models
from django.utils import timezone
from django.urls import reverse

from taggit.managers import TaggableManager


class PublishManager(models.Manager):
    # Менеджер модели по умолчанию для .all()
    def get_queryset(self):
        # делаем фильтрованный запрос
        return super().get_queryset().filter(status='published')


class Post(models.Model):
    # Список статусов
    STATUS_CHOICES = (
        ('draft', 'Черновик'),
        ('published', 'Опубликована'),
    )

    tags = TaggableManager()

    # Заголовок статьи
    title = models.CharField(max_length=50)
    # Для формирования уникальный URL
    slug = models.SlugField(max_length=250, unique_for_date='publish')
    # внешний ключ. один ко многим, удаление вместе с записями, обратная связь User to Post
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='blog_post')
    # содержание статьи
    body = models.TextField()
    # Дата публикации текущие дата и время с учетом временной зоны.
    publish = models.DateTimeField(default=timezone.now)
    # указатель на то когда была создана, указывается автоматически при создании объекта
    created = models.DateTimeField(auto_now_add=True)
    # -||- когда была отредактирована, при сохранении автообновляется
    updated = models.DateTimeField(auto_now=True)
    # статус статьи ( на выбор 2 варианта
    status = models.CharField(choices=STATUS_CHOICES, max_length=50, default='draft')
    # Менеджер по умолчанию
    objects = models.Manager()
    # Новый менеджер published
    published = PublishManager()

    def get_absolute_url(self):
        b = Post.objects.get(pk=self.pk).created.astimezone(timezone.get_current_timezone())
        return reverse('blog:post_detail', args=[b.year,
                                                 b.month,
                                                 b.day,
                                                 self.slug])

    class Meta:
        # Порядок сортировки статей убывающий (последние будут первыми)
        ordering = ('-publish',)

    def __str__(self):
        # Для админки
        return self.title

    def __repr__(self):
        return self.title


class Comment(models.Model):
    # для привязки к определенной статье ( один ко многим) одна статья может иметь множество комментариев,
    # но каждый комментарий может быть оставлен только к одной статье.
    # related_name - для обращения по post.comments.all() ( по default = _set, comment_set)
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='comments')

    name = models.CharField(max_length=50)
    email = models.EmailField()
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    # для скрытия некоторых комментариев
    active = models.BooleanField(default=True)

    class Meta:
        ordering = ('created',)

    def __str__(self):
        return f'Comment by {self.name} on {self.post}'

blog/views.py
from django.core.mail import send_mail
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.db.models import Count
from django.shortcuts import render, get_object_or_404
from django.contrib.postgres.search import SearchVector, SearchQuery, SearchRank

from taggit.models import Tag

from .form import EmailPostForm, CommentForm, SearchForm
from .models import Post, Comment


def post_search(request):
    form = SearchForm()
    query = None
    results = []
    if 'query' in request.GET:
        form = SearchForm(request.GET)
    if form.is_valid():
        query = form.cleaned_data['query']
        search_vector = SearchVector('title', weight='A') + SearchVector('body', weight='B')
        search_query = SearchQuery(query)
        results = Post.published.annotate(search=search_vector, rank=SearchRank(search_vector, search_query)
                                          ).filter(search=query).order_by('-rank')

    return render(request, 'blog/post/search.html', {'form': form,
                                                     'query': query,
                                                     'results': results})


def post_list(request, tag_slug=None):
    # tag_slug: Передается через ссылку URL
    # получаем все записи из базы данных
    # (применяя менеджер модели получаем только 'published')
    object_list = Post.published.all()
    tag = None
    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug, )
        object_list = object_list.filter(tags__in=[tag])

    paginator = Paginator(object_list, 3)  # по 3 статьи на каждой странице

    # Получаем номер строки из - url
    page = request.GET.get('page')

    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        # Если страница не является целым числом, возвращаем первую страницу.
        posts = paginator.page(1)
    except EmptyPage:
        # Если номер страницы больше, чем общее количество страниц, возвращаем последнюю страницу.
        posts = paginator.page(paginator.num_pages)
    return render(request, 'blog/post/list.html', {'page': page, 'posts': posts, 'tag': tag})


# class PostListView(ListView):
#     # Используем переопределенный менеджер модели, для получения обычного
#     queryset = Post.published.all()  # ListView
#     context_object_name = 'posts'
#     paginate_by = 3
#     template_name = 'blog/post/list.html'


def post_detail(request, year, month, day, post):
    # возвращает 404 если объект не найден
    post = get_object_or_404(Post,
                             slug=post,
                             status='published',
                             publish__year=year,
                             publish__month=month,
                             publish__day=day)

    # Список активных комментариев для этой статьи.
    comments = post.comments.filter(active=True)
    new_comment = None
    if request.method == 'POST':
        # пользователь отправил комментарий.
        comment_form = CommentForm(data=request.POST)
        if comment_form.is_valid():
            # Создаем комментарий, но пока не сохраняем в БД(commit=False).
            new_comment = comment_form.save(commit=False)
            # Привязываем комментарий к текущей статье.
            new_comment.post = post
            # Сохраняем комментарий в базе данных.
            new_comment.save()
    else:
        comment_form = CommentForm()

    # Получаем все id тегов текущей статьи
    # вида <QuerySet [3, 4, 6]>
    post_tags_ids = post.tags.values_list('id', flat=True)
    # Получаем все статьи содержащие хоть один тег из полученных ранее, исключая текущую статью
    similar_posts = Post.published.filter(tags__in=post_tags_ids).exclude(id=post.id)
    similar_posts = similar_posts.annotate(same_tags=Count('tags')).order_by('-same_tags', '-publish')[:4]

    return render(request, 'blog/post/detail.html', {'post': post,
                                                     'comments': comments,
                                                     'new_comment': new_comment,
                                                     'comment_form': comment_form,
                                                     'similar_posts': similar_posts})


def post_share(request, post_id):
    # Получение статьи по идентификатору.
    post = get_object_or_404(Post, id=post_id, status='published')
    sent = False

    if request.method == 'POST':
        # Форма была отправлена на сохранение.
        form = EmailPostForm(request.POST)
        if form.is_valid():
            # Все поля формы прошли валидацию.
            cd = form.cleaned_data  # в словарь попадают только корректные поля
            # Отправка письма
            post_url = request.build_absolute_uri(post.get_absolute_url())
            subject = '{} ({}) recommends you reading "{}"'.format(cd['name'], cd['email'], post.title)
            message = 'Read "{}" at {}\n\n{}\'s comments: {}'.format(post.title, post_url, cd['name'], cd['comments'])
            send_mail(subject, message, 'admin@myblog.com', [cd['to']])
            sent = True

    else:  # Вариант если GET отправляем пустую форму
        form = EmailPostForm()
    return render(request, 'blog/post/share.html', {'post': post, 'form': form, 'sent': sent})

blog/templates/blog/post/detail.html
{% extends 'blog/base.html' %}
{% load blog_tags %}
{% block title %} {{ post.title }} {% endblock %}
{% block content %}
    <h1>{{ post.title }}</h1>
    <p class="date">Опубликован{{ post.publish }} автор - {{ post.author|upper }}</p>
    {{ post.body|markdown }}
    <p>
        <a href="{% url 'blog:post_share' post.id %}">Share this post</a>
    </p>
    {% with comments.count as total_comments %}
        <h2>{{ total_comments }} comment{{ total_comments|pluralize }}</h2>
    {% endwith %}
    {% for comment in comments %}
        <div class="comment">
            <p class="info">
                Comment {{ forloop.counter }} by {{ comment.name }}
                {{ comment.body|linebreaks }}
            </p>
        </div>
    {% empty %}
        <p>There are no comments yet.</p>
    {% endfor %}

    {% for tag in post.tags.all %}

        <a href="{% url 'blog:post_list_by_tag' tag.slug %}">
            {{ tag.name }}
        </a>
        {% if not forloop.last %}, {% endif %}
    {% endfor %}

    {% if new_comment %}
        <h2>Your comment has ben added</h2>
    {% else %}
        <h2>Аdd a new comment</h2>
        <form action="." method="post">
            {{ comment_form.as_p }}
            {% csrf_token %}
            <p><input type="submit" value="Add comment"></p>
        </form>
    {% endif %}

{% endblock %}

blog/templates/blog/post/latest_post.html
<ul>
    {% for post in latest_posts %}
        <li><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></li>
    {% endfor %}

</ul>

blog/templates/blog/post/list.html
{% extends 'blog/base.html' %}
{% load blog_tags %}
{% load tz %}
{% block title %}My blog{% endblock title %}
{% block content %}

    <div class="post-title"><h1> My blog </h1></div>
    {% if tag %}
        <h2>Post tagged with "{{ tag.name }}"</h2>
    {% endif %}
    {% for post in posts %}
        <h2>
            <a href="{{ post.get_absolute_url }}"> {{ post.title }}</a>
        </h2>
        {% timezone "Europe/Moscow" %}

            <p class="date">Published {{ post.publish }} by {{ post.author }}</p>
            {{ post.body|markdown|truncatewords_html:30 }}
            <p class="tags">
                {#            Tags: {{ post.tags.all|join:", " }}#}
                Tags:
                {% for tag in post.tags.all %}

                    <a href="{% url 'blog:post_list_by_tag' tag.slug %}">
                        {{ tag.name }}
                    </a>
                    {% if not forloop.last %}, {% endif %}
                {% endfor %}

            </p>
        {% endtimezone %}

    {% endfor %}
    {% include "blog/pagination.html" with page=posts %}
    {#    {% include "big_site/pagination.html" with page=page_obj %}#}
{% endblock %}

blog/templates/blog/post/search.html
{% extends "blog/base.html" %}

{% block title %} Search {% endblock %}

{% block content %}
    {% if query %}
        <h1>Posts containing "{{ query }}"</h1>
        <h3>
            {% with results.count as total_results %}
                Found {{ total_results }} result {{ total_results|pluralize }}
            {% endwith %}
        </h3>
        {% for post in results %}
            <h4><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></h4>
            {{ post.body|truncatewords:5 }}
        {% empty %}
            <p>There are no results for your query</p>
        {% endfor %}
        <p><a href="{% url 'blog:post_search' %}">Search again</a></p>
    {% else %}
        <h1>Search for posts</h1>
        <form action="." method="get">
            {{ form.as_p }}
            <input type="submit" value="Search">
        </form>

    {% endif %}
{% endblock %}

blog/templates/blog/post/share.html
{% extends 'blog/base.html' %}
{% block title %}Share a post{% endblock title %}
{% block content %}
    {% if sent %}
        <h1>Email successfully sent</h1>
        <p>"{{ post.title }}" was successfully sent to {{ form.cleaned_data.to }}.</p>
    {% else %}
        <h1>Share "{{ post.title }}" by e-mail</h1>
        <form action="." method="post">
            {{ form.as_p }}
            {#                        as_ul, as_table#}
            {% csrf_token %}
            <input type="submit" value="Send e-mail">
        </form>
    {% endif %}
{% endblock %}